# Nome do workflow (aparece na aba Actions do seu repositório)
name: github-actions-dotnet-webapp

on:
  push:
    branches:
      - main

  # Aciona agendamento (a cada hora)
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    #ambiente onde o job será executado (máquina virtual)
    runs-on: ubuntu-latest

    steps:
      # Action pré-existente: faz checkout do repositório
      - name: Checkout repository code
        uses: actions/checkout@v4 

      # Action personalizada
      - name: Executar script personalizado
        run: |
          echo "Workflow acionado por: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Acionado por push no commit: ${{ github.sha }}"
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Acionado por agendamento (cron: 0 * * * *)"
          fi
          echo "Data e Hora atuais: $(date)"